# Preprocess the data

## Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

## Selecting the data

In [2]:
raw_data = pd.read_csv('Dow_061719_061720_full.csv')
raw_data

,Company,Date,Open,High,Low,Close,Adj Close,Volume,Yesterday Change,% Yesterday Change,Average 5-Day Change,% 5-Day Change,Average 10-Day Change,% 10-Day Change,EOD High
0,AAPL,6/17/2019,192.899994,194.960007,192.169998,193.889999,191.603317,14669100,0.990005,0.005106,0.332004,0.001679,0.030005,0.000152,1
1,AAPL,6/18/2019,196.050003,200.289993,195.210007,198.449997,196.109528,26551000,0.990005,0.005106,0.332004,0.001679,0.030005,0.000152,1
2,AAPL,6/19/2019,199.679993,199.880005,197.309998,197.869995,195.536377,21124200,2.399994,0.012094,0.332004,0.001679,0.030005,0.000152,0
3,AAPL,6/20/2019,200.369995,200.610001,198.029999,199.460007,197.107620,21514000,-1.809998,-0.009147,0.332004,0.001679,0.030005,0.000152,0
4,AAPL,6/21/2019,198.800003,200.850006,198.149994,198.779999,196.435623,47800600,-0.909988,-0.004562,0.332004,0.001679,0.030005,0.000152,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7361,XOM,6/11/2020,47.529999,48.840000,46.099998,46.180000,46.180000,39183000,-2.849998,-0.056268,0.710000,0.013597,0.380000,0.007686,0
7362,XOM,6/12/2020,48.040001,48.619999,45.910000,47.169998,47.169998,30968800,-1.349999,-0.029233,-0.108000,-0.002092,0.137000,0.002764,0
7363,XOM,6/15/2020,45.349998,47.759998,44.750000,47.139999,47.139999,27929300,-0.870003,-0.018444,-0.421999,-0.008364,0.141000,0.002835,1
7364,XOM,6/16/2020,49.570000,49.750000,47.240002,48.200001,48.200001,26183400,1.790001,0.037972,-0.882000,-0.018025,-0.011000,-0.000221,0
7365,XOM,6/17/2020,48.000000,48.130001,46.610001,46.619999,46.619999,17077752,-1.369999,-0.028423,-0.528000,-0.011030,0.072000,0.001443,0

In [3]:
data = raw_data.iloc[:,0:6]
data

     Company       Date        Open        High         Low       Close
0       AAPL  6/17/2019  192.899994  194.960007  192.169998  193.889999
1       AAPL  6/18/2019  196.050003  200.289993  195.210007  198.449997
2       AAPL  6/19/2019  199.679993  199.880005  197.309998  197.869995
3       AAPL  6/20/2019  200.369995  200.610001  198.029999  199.460007
4       AAPL  6/21/2019  198.800003  200.850006  198.149994  198.779999
...      ...        ...         ...         ...         ...         ...
7361     XOM  6/11/2020   47.529999   48.840000   46.099998   46.180000
7362     XOM  6/12/2020   48.040001   48.619999   45.910000   47.169998
7363     XOM  6/15/2020   45.349998   47.759998   44.750000   47.139999
7364     XOM  6/16/2020   49.570000   49.750000   47.240002   48.200001
7365     XOM  6/17/2020   48.000000   48.130001   46.610001   46.619999

[7366 rows x 6 columns]

In [4]:
data.Company.unique()

array(['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'DIS', 'DOW', 'GS', 'HD',
       'IBM', 'CVX', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 'MRK',
       'MSFT', 'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'V', 'VZ', 'WBA', 'WMT',
       'XOM'], dtype=object)

# Analyze each company

## AAPL

### Select the data

It could be made better by breaking it down into months or even weeks and calculating the statistics based on that

In [5]:
c_data = data.loc[data['Company'] == 'AAPL']
c_data = c_data.drop(['Company', 'Date'], axis=1)
c_data

           Open        High         Low       Close
0    192.899994  194.960007  192.169998  193.889999
1    196.050003  200.289993  195.210007  198.449997
2    199.679993  199.880005  197.309998  197.869995
3    200.369995  200.610001  198.029999  199.460007
4    198.800003  200.850006  198.149994  198.779999
..          ...         ...         ...         ...
249  349.309998  351.059998  335.480011  335.899994
250  344.720001  347.799988  334.220001  338.799988
251  333.250000  345.679993  332.579987  342.989990
252  351.459991  353.200012  344.720001  352.079987
253  355.149994  355.369995  351.089996  351.589996

[254 rows x 4 columns]

### Get descriptive statistics|

In [6]:
high_col = c_data['High']
low_col = c_data['Low']
high = high_col.mean()
low = low_col.mean()
high, low

(263.9953148149608, 258.0036617322836)

## Calculate the total money at the end of the year using average

In [7]:
total_money_gained = 0 
stock_number = 0
money_in_market = 0
print("It's the beginning")
for i, j in c_data.iterrows():
    if j.Open < 260.75:
        total_money_gained -= j.Open
        stock_number += 1
        money_in_market += j.Open
        print("Buying one stock while it is low")
        print('Stock Number '+str(stock_number))
        print('Money in the market '+str(money_in_market))
        print('Total money gained '+str(total_money_gained))
        print('\n')
    elif j.Open > 265.33 and stock_number>0:
        total_money_gained += stock_number*j.Open
        stock_number = 0
        money_in_market = 0
        print("Selling all stocks while they are high")
        print('Stock Number '+str(stock_number))
        print('Money in the market '+str(money_in_market))
        print('Total money gained '+str(total_money_gained))
        print('\n')
    elif j.Close < 260.75:
        total_money_gained -= j.Open
        stock_number += 1
        money_in_market += j.Open
        print("Buying one stock while it is low")
        print('Stock Number '+str(stock_number))
        print('Money in the market '+str(money_in_market))
        print('Total money gained '+str(total_money_gained))
        print('\n')
    elif j.Close > 265.33 and stock_number>0:
        total_money_gained += stock_number*j.Open
        stock_number = 0
        money_in_market = 0
        print("Selling all stocks while they are high")
        print('Stock Number '+str(stock_number))
        print('Money in the market '+str(money_in_market))
        print('Total money gained '+str(total_money_gained))
        print('\n')
    else:
        print('Doing nothing')
        print('Stock Number '+str(stock_number))
        print('Money in the market '+str(money_in_market))
        print('Total money gained '+str(total_money_gained))
        print('\n')
        
print('Money at the end of the year: '+str(total_money_gained+money_in_market))

It's the beginning
Buying one stock while it is low
Stock Number 1
Money in the market 192.899994
Total money gained -192.899994


Buying one stock while it is low
Stock Number 2
Money in the market 388.949997
Total money gained -388.949997


Buying one stock while it is low
Stock Number 3
Money in the market 588.62999
Total money gained -588.62999


Buying one stock while it is low
Stock Number 4
Money in the market 788.999985
Total money gained -788.999985


Buying one stock while it is low
Stock Number 5
Money in the market 987.799988
Total money gained -987.799988


Buying one stock while it is low
Stock Number 6
Money in the market 1186.339981
Total money gained -1186.339981


Buying one stock while it is low
Stock Number 7
Money in the market 1384.769974
Total money gained -1384.769974


Buying one stock while it is low
Stock Number 8
Money in the market 1582.539978
Total money gained -1582.539978


Buying one stock while it is low
Stock Number 9
Money in the market 1782.8299710000001
Total money gained -1782.8299710000001


Buying one stock while it is low
Stock Number 10
Money in the market 1981.509964
Total money gained -1981.509964


Buying one stock while it is low
Stock Number 11
Money in the market 2184.679962
Total money gained -2184.679962


Buying one stock while it is low
Stock Number 12
Money in the market 2386.089966
Total money gained -2386.089966


Buying one stock while it is low
Stock Number 13
Money in the market 2589.369965
Total money gained -2589.369965


Buying one stock while it is low
Stock Number 14
Money in the market 2792.719971
Total money gained -2792.719971


Buying one stock while it is low
Stock Number 15
Money in the market 2993.529969
Total money gained -2993.529969


Buying one stock while it is low
Stock Number 16
Money in the market 3192.7299660000003
Total money gained -3192.7299660000003


Buying one stock while it is low
Stock Number 17
Money in the market 3394.5799720000005
Total money gained -3394.5799720000005


Buying one stock while it is low
Stock Number 18
Money in the market 3597.8899700000006
Total money gained -3597.8899700000006


Buying one stock while it is low
Stock Number 19
Money in the market 3800.339967000001
Total money gained -3800.339967000001


Buying one stock while it is low
Stock Number 20
Money in the market 4004.429963000001
Total money gained -4004.429963000001


Buying one stock while it is low
Stock Number 21
Money in the market 4209.019959000001
Total money gained -4209.019959000001


Buying one stock while it is low
Stock Number 22
Money in the market 4413.069962000001
Total money gained -4413.069962000001


Buying one stock while it is low
Stock Number 23
Money in the market 4617.069962000001
Total money gained -4617.069962000001


Buying one stock while it is low
Stock Number 24
Money in the market 4822.859955000002
Total money gained -4822.859955000002


Buying one stock while it is low
Stock Number 25
Money in the market 5026.509949000002
Total money gained -5026.509949000002


Buying one stock while it is low
Stock Number 26
Money in the market 5234.969956000002
Total money gained -5234.969956000002


Buying one stock while it is low
Stock Number 27
Money in the market 5442.639954000002
Total money gained -5442.639954000002


Buying one stock while it is low
Stock Number 28
Money in the market 5651.529953000002
Total money gained -5651.529953000002


Buying one stock while it is low
Stock Number 29
Money in the market 5859.009949000002
Total money gained -5859.009949000002


Buying one stock while it is low
Stock Number 30
Money in the market 6067.469956000002
Total money gained -6067.469956000002


Buying one stock while it is low
Stock Number 31
Money in the market 6276.229951000002
Total money gained -6276.229951000002


Buying one stock while it is low
Stock Number 32
Money in the market 6492.649949000002
Total money gained -6492.649949000002


Buying one stock while it is low
Stock Number 33
Money in the market 6706.549943000003
Total money gained -6706.549943000003


Buying one stock while it is low
Stock Number 34
Money in the market 6912.079942000003
Total money gained -6912.079942000003


Buying one stock while it is low
Stock Number 35
Money in the market 7110.069947000003
Total money gained -7110.069947000003


Buying one stock while it is low
Stock Number 36
Money in the market 7306.379945000002
Total money gained -7306.379945000002


Buying one stock while it is low
Stock Number 37
Money in the market 7501.789949000003
Total money gained -7501.789949000003


Buying one stock while it is low
Stock Number 38
Money in the market 7701.989946000002
Total money gained -7701.989946000002


Buying one stock while it is low
Stock Number 39
Money in the market 7903.289949000003
Total money gained -7903.289949000003


Buying one stock while it is low
Stock Number 40
Money in the market 8102.909944000003
Total money gained -8102.909944000003


Buying one stock while it is low
Stock Number 41
Money in the market 8303.929948000003
Total money gained -8303.929948000003


Buying one stock while it is low
Stock Number 42
Money in the market 8507.089952000002
Total money gained -8507.089952000002


Buying one stock while it is low
Stock Number 43
Money in the market 8710.549959000002
Total money gained -8710.549959000002


Buying one stock while it is low
Stock Number 44
Money in the market 8914.829958000002
Total money gained -8914.829958000002


Buying one stock while it is low
Stock Number 45
Money in the market 9125.449953000003
Total money gained -9125.449953000003


Buying one stock while it is low
Stock Number 46
Money in the market 9336.329958000002
Total money gained -9336.329958000002


Buying one stock while it is low
Stock Number 47
Money in the market 9549.319963000002
Total money gained -9549.319963000002


Buying one stock while it is low
Stock Number 48
Money in the market 9762.509965000001
Total money gained -9762.509965000001


Buying one stock while it is low
Stock Number 49
Money in the market 9971.939958
Total money gained -9971.939958


Buying one stock while it is low
Stock Number 50
Money in the market 10177.799959
Total money gained -10177.799959


Buying one stock while it is low
Stock Number 51
Money in the market 10385.65996
Total money gained -10385.65996


Buying one stock while it is low
Stock Number 52
Money in the market 10589.759966000001
Total money gained -10589.759966000001


Buying one stock while it is low
Stock Number 53
Money in the market 10798.259966000001
Total money gained -10798.259966000001


Buying one stock while it is low
Stock Number 54
Money in the market 11008.41997
Total money gained -11008.41997


Buying one stock while it is low
Stock Number 55
Money in the market 11214.849963
Total money gained -11214.849963


Buying one stock while it is low
Stock Number 56
Money in the market 11423.239962
Total money gained -11423.239962


Buying one stock while it is low
Stock Number 57
Money in the market 11635.239962
Total money gained -11635.239962


Buying one stock while it is low
Stock Number 58
Money in the market 11849.289965
Total money gained -11849.289965


Buying one stock while it is low
Stock Number 59
Money in the market 12064.129961
Total money gained -12064.129961


Buying one stock while it is low
Stock Number 60
Money in the market 12277.989962
Total money gained -12277.989962


Buying one stock while it is low
Stock Number 61
Money in the market 12496.059969
Total money gained -12496.059969


Buying one stock while it is low
Stock Number 62
Money in the market 12720.859972
Total money gained -12720.859972


Buying one stock while it is low
Stock Number 63
Money in the market 12940.859972
Total money gained -12940.859972


Buying one stock while it is low
Stock Number 64
Money in the market 13158.589968
Total money gained -13158.589968


Buying one stock while it is low
Stock Number 65
Money in the market 13378.549975
Total money gained -13378.549975


Buying one stock while it is low
Stock Number 66
Money in the market 13599.609973
Total money gained -13599.609973


Buying one stock while it is low
Stock Number 67
Money in the market 13821.619968
Total money gained -13821.619968


Buying one stock while it is low
Stock Number 68
Money in the market 14042.999973000002
Total money gained -14042.999973000002


Buying one stock while it is low
Stock Number 69
Money in the market 14261.949970000001
Total money gained -14261.949970000001


Buying one stock while it is low
Stock Number 70
Money in the market 14482.979969000002
Total money gained -14482.979969000002


Buying one stock while it is low
Stock Number 71
Money in the market 14701.529972000002
Total money gained -14701.529972000002


Buying one stock while it is low
Stock Number 72
Money in the market 14921.529972000002
Total money gained -14921.529972000002


Buying one stock while it is low
Stock Number 73
Money in the market 15142.069965000002
Total money gained -15142.069965000002


Buying one stock while it is low
Stock Number 74
Money in the market 15362.969959000002
Total money gained -15362.969959000002


Buying one stock while it is low
Stock Number 75
Money in the market 15588.039966000002
Total money gained -15588.039966000002


Buying one stock while it is low
Stock Number 76
Money in the market 15811.099964000003
Total money gained -15811.099964000003


Buying one stock while it is low
Stock Number 77
Money in the market 16029.529957000002
Total money gained -16029.529957000002


Buying one stock while it is low
Stock Number 78
Money in the market 16255.169956000003
Total money gained -16255.169956000003


Buying one stock while it is low
Stock Number 79
Money in the market 16481.439960000003
Total money gained -16481.439960000003


Buying one stock while it is low
Stock Number 80
Money in the market 16707.259967
Total money gained -16707.259967


Buying one stock while it is low
Stock Number 81
Money in the market 16934.289966
Total money gained -16934.289966


Buying one stock while it is low
Stock Number 82
Money in the market 17162.219959000002
Total money gained -17162.219959000002


Buying one stock while it is low
Stock Number 83
Money in the market 17395.169956
Total money gained -17395.169956


Buying one stock while it is low
Stock Number 84
Money in the market 17630.06995
Total money gained -17630.06995


Buying one stock while it is low
Stock Number 85
Money in the market 17866.459949
Total money gained -17866.459949


Buying one stock while it is low
Stock Number 86
Money in the market 18099.829944
Total money gained -18099.829944


Buying one stock while it is low
Stock Number 87
Money in the market 18334.91994
Total money gained -18334.91994


Buying one stock while it is low
Stock Number 88
Money in the market 18569.509936
Total money gained -18569.509936


Buying one stock while it is low
Stock Number 89
Money in the market 18807.02994
Total money gained -18807.02994


Buying one stock while it is low
Stock Number 90
Money in the market 19048.189944
Total money gained -19048.189944


Buying one stock while it is low
Stock Number 91
Money in the market 19290.289950000002
Total money gained -19290.289950000002


Buying one stock while it is low
Stock Number 92
Money in the market 19534.799945000002
Total money gained -19534.799945000002


Buying one stock while it is low
Stock Number 93
Money in the market 19777.959949000004
Total money gained -19777.959949000004


Buying one stock while it is low
Stock Number 94
Money in the market 20025.379947000005
Total money gained -20025.379947000005


Buying one stock while it is low
Stock Number 95
Money in the market 20274.349948000006
Total money gained -20274.349948000006


Buying one stock while it is low
Stock Number 96
Money in the market 20519.109943000007
Total money gained -20519.109943000007


Buying one stock while it is low
Stock Number 97
Money in the market 20766.349948000006
Total money gained -20766.349948000006


Buying one stock while it is low
Stock Number 98
Money in the market 21015.889941000005
Total money gained -21015.889941000005


Buying one stock while it is low
Stock Number 99
Money in the market 21273.219928000006
Total money gained -21273.219928000006


Buying one stock while it is low
Stock Number 100
Money in the market 21530.269916000005
Total money gained -21530.269916000005


Buying one stock while it is low
Stock Number 101
Money in the market 21787.039905000005
Total money gained -21787.039905000005


Buying one stock while it is low
Stock Number 102
Money in the market 22045.779895000003
Total money gained -22045.779895000003


Buying one stock while it is low
Stock Number 103
Money in the market 22304.469897000003
Total money gained -22304.469897000003


Buying one stock while it is low
Stock Number 104
Money in the market 22562.769885
Total money gained -22562.769885


Doing nothing
Stock Number 104
Money in the market 22562.769885
Total money gained -22562.769885


Doing nothing
Stock Number 104
Money in the market 22562.769885
Total money gained -22562.769885


Doing nothing
Stock Number 104
Money in the market 22562.769885
Total money gained -22562.769885


Selling all stocks while they are high
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4859.949387000001


Buying one stock while it is low
Stock Number 1
Money in the market 258.309998
Total money gained 4601.639389000001


Doing nothing
Stock Number 1
Money in the market 258.309998
Total money gained 4601.639389000001


Selling all stocks while they are high
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4865.429398000001


Buying one stock while it is low
Stock Number 1
Money in the market 257.26001
Total money gained 4608.169388000001


Selling all stocks while they are high
Stock Number 0
Money in the market 0
Total money gained 4890.4493870000015


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4890.4493870000015


Doing nothing
Stock Number 0
Money in the market 0
Total money gained 4890.4493870000015


Doing nothing
Stock Number 0
Money in the market 0

# Create Function

In [8]:
def mean_reversion(data, low, high):
    total_money_gained = 0 
    stock_number = 0
    money_in_market = 0
    for i, j in data.iterrows():
        if j.Open < low:
            total_money_gained -= j.Open
            stock_number += 1
            money_in_market += j.Open
        elif j.Open > high and stock_number>0:
            total_money_gained += stock_number*j.Open
            stock_number = 0
            money_in_market = 0
        elif j.Close < low:
            total_money_gained -= j.Open
            stock_number += 1
            money_in_market += j.Open
        elif j.Close > high and stock_number>0:
            total_money_gained += stock_number*j.Open
            stock_number = 0
            money_in_market = 0
    return (total_money_gained+money_in_market)

## Test function

In [9]:
print(mean_reversion(c_data, 260.75, 265.33))

5307.059209

### Automate

In [10]:
companies = data.Company.unique()
companies

array(['AAPL', 'AXP', 'BA', 'CAT', 'CSCO', 'DIS', 'DOW', 'GS', 'HD',
       'IBM', 'CVX', 'INTC', 'JNJ', 'JPM', 'KO', 'MCD', 'MMM', 'MRK',
       'MSFT', 'NKE', 'PFE', 'PG', 'TRV', 'UNH', 'V', 'VZ', 'WBA', 'WMT',
       'XOM'], dtype=object)

In [11]:
company_name = []
money = []
high_list = []
low_list =[]

for i in range(companies.size):
    c_data = data.loc[data['Company'] == str(companies[i])]
    c_data = c_data.drop(['Company','Date'], axis=1)
    high_col = c_data['High']
    low_col = c_data['Low']
    high = high_col.mean()
    low = low_col.mean()
    company_name.append(str(companies[i]))
    money.append(mean_reversion(c_data, low, high))
    high_list.append(high)
    low_list.append(low)
    
summary = pd.DataFrame(columns=['Company', 'Total', 'High', 'Low'])
summary['Company'] = company_name
summary['Total'] = money
summary['High'] = high_list
summary['Low'] = low_list
summary

   Company        Total        High         Low
0     AAPL  5028.720411  263.995315  258.003662
1      AXP     4.540001  115.097559  112.292244
2       BA     0.000000  297.219016  287.967992
3      CAT  2064.040434  130.081614  126.799252
4     CSCO   488.150050   47.539213   46.444921
5      DIS     3.929993  131.228189  128.179606
6      DOW   763.410113   45.567197   44.077673
7       GS  2712.129658  208.848347  203.779646
8       HD  1986.399713  224.179646  219.302835
9      IBM   978.870213  134.746181  131.978819
10     CVX     1.909997  109.575079  107.089764
11    INTC   771.140137   56.247559   54.771220
12     JNJ   993.130618  140.009094  137.337520
13     JPM   279.219994  116.248307  113.618543
14      KO    20.870000   52.558583   51.588976
15     MCD   222.020274  201.025118  197.083307
16     MMM  1570.870012  163.247516  159.517549
17     MRK    43.439971   84.021378   82.237303
18    MSFT  2368.300633  156.761851  153.246063
19     NKE   992.920065   91.795669   89.692165
20     PFE   299.960028   37.718957   36.943051
21      PG   511.370037  120.207638  117.796299
22     TRV     0.000000  131.488504  128.649291
23     UNH  3623.539930  267.940709  260.448780
24       V  1453.499814  183.423780  179.414922
25      VZ   217.270099   58.423622   57.416181
26     WBA   121.089971   52.292323   50.822992
27     WMT   665.430190  118.544173  116.263976
28     XOM     5.209998   62.402559   60.989528

In [12]:
summary['Total'].sum()

28191.382354